### PR TITLE
Badfish patch

### PR DESCRIPTION
**Pull request by mukrishn**
# Description
Latest Badfish has some issues on using virtual python environment and venv will [not be supported](https://github.com/redhat-performance/JetSki/issues/186#issuecomment-982666646) in the long run. 
error:
```
File \"./src/badfish/badfish.py\", line 24, in <module>\n    from src.badfish.helpers.async_lru import alru_cache\nModuleNotFoundError│···································: No module named 'src'", "stderr_lines": ["Traceback (most recent call last):", "  File \"./src/badfish/badfish.py\", line 24, in <module>", "    from src.badfish.helpers.async_lru import alru_cache", "ModuleNotFoundError: No module named 'src'"], "stdout": "", "stdout_lines": []}
```

Updating this to use podman image instead.

Fixes # (issue)

## Type of change

Please select the appropriate options:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change is a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested on r650 cloud by @sferlin 

**Test Configuration**:

- Versions: 4.10/4.11
- Hardware: r650

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not be merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by sferlin** [comment]
@mukrishn : applied your fix and it is fixed.

**Review by dustinblack — CHANGES_REQUESTED** [review]
So it turns out that we handle badfish commands separately and in different ways across three different roles. This change obviously needs to be made, but it seems we've actually already done it this way in the bootstrap role.

https://github.com/redhat-performance/JetSki/blob/ab0bba1094226119fca1f7feb4bdc3b73d6c67e9/ansible-ipi-install/roles/bootstrap/vars/main.yml#L2

But the scale-node-prep role seems to still use the venv approach.

https://github.com/redhat-performance/JetSki/blob/ab0bba1094226119fca1f7feb4bdc3b73d6c67e9/ansible-ipi-install/roles/scale-node-prep/vars/main.yml#L2

And strangely the bootstrap role seems to use both approaches.

https://github.com/redhat-performance/JetSki/blob/ab0bba1094226119fca1f7feb4bdc3b73d6c67e9/ansible-ipi-install/roles/bootstrap/vars/main.yml#L3
https://github.com/redhat-performance/JetSki/blob/ab0bba1094226119fca1f7feb4bdc3b73d6c67e9/ansible-ipi-install/roles/bootstrap/tasks/20_reprovision_nodes.yml#L126

I think we need to adjust this PR to address the inconsistencies and ensure the venv approach is removed globally.

This could affect #226 and #108.

**Comment by mukrishn** [comment]
> So it turns out that we handle badfish commands separately and in different ways across three different roles. This change obviously needs to be made, but it seems we've actually already done it this way in the bootstrap role.
> 
> https://github.com/redhat-performance/JetSki/blob/ab0bba1094226119fca1f7feb4bdc3b73d6c67e9/ansible-ipi-install/roles/bootstrap/vars/main.yml#L2
> 
> But the scale-node-prep role seems to still use the venv approach.
> 
> https://github.com/redhat-performance/JetSki/blob/ab0bba1094226119fca1f7feb4bdc3b73d6c67e9/ansible-ipi-install/roles/scale-node-prep/vars/main.yml#L2
> 

Thanks, updated here :+1: 
> And strangely the bootstrap role seems to use both approaches.
> 
> https://github.com/redhat-performance/JetSki/blob/ab0bba1094226119fca1f7feb4bdc3b73d6c67e9/ansible-ipi-install/roles/bootstrap/vars/main.yml#L3
> 
> 
> https://github.com/redhat-performance/JetSki/blob/ab0bba1094226119fca1f7feb4bdc3b73d6c67e9/ansible-ipi-install/roles/bootstrap/tasks/20_reprovision_nodes.yml#L126
> 
> I think we need to adjust this PR to address the inconsistencies and ensure the venv approach is removed globally.
> 
> This could affect #226 and #108.


Yes, bootstrap role still needs venv(or [CLI](https://github.com/redhat-performance/badfish#badfish-standalone-cli)) approach when running JetSki playbook from a pod (in case of airflow).

**Comment by dustinblack** [comment]
Validated the latest patches with a lab of fc640 nodes today. All good!

**Comment by mukrishn** [comment]
cool, we can completely get rid off `venv` and replace it with badfish CLI commands IMO.

**Pull request merged**
