### PR TITLE
[draft] More JetSki containerization

### PR DESCRIPTION
**Pull request by sarahbx**
# Description

I am currently on a mac for development, so I utilize the containerization to simplify my runtime environment.
Initially developed on docker, I have switched to `podman --remote` support for podman within a centos8 stream VM. 

* Will retest this when I perform my next deploy
* Support for running rootless container on RHEL or Fedora has not been verified

Example usage: `./run-jetski-container.sh ~/.ssh/id_rsa ansible-ipi-install/playbook-jetski.yml`

Open to feedback

Fixes # (issue)

## Type of change

Please select the appropriate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ? ] New feature (non-breaking change which adds functionality)
- [ ? ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [ ] This change is a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not be merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by sarahbx** [comment]
I have added `podman --remote` support for `podman` within a centos8 stream VM.

* Will retest this whenever I perform my next deploy
* Support for running rootless container on RHEL or Fedora has not been verified

**Comment by smalleni** [comment]
@sarahbx Any update here?

**Comment by sarahbx** [comment]
HI @smalleni, Unfortunately, the deploys I've needed to do are time sensitive, so am still using https://github.com/redhat-performance/JetSki/commit/434790f8bc3fecfd0f19ffc58bde60ada40fb386 for current deploys and debugging the newer rev as I am able.

**Comment by dustinblack** [comment]
@sarahbx Do you want to revisit this, or should we go ahead and close it out?

**Pull request closed without merging**
