### PR TITLE
upstream rebase and fixed hostname issue

### PR DESCRIPTION
**Pull request by mukrishn**
# Description

Rebased from upstream openshift-kni/baremetal-deploy

fix to disable hostname from lab dhcp server and public interface during first boot - [slack thread](https://redhat-internal.slack.com/archives/C04SZGZDBRD/p1710854055883429)

Fixes # (issue)

Added a new nmstate config for day-1 installation - [link](https://github.com/openshift-kni/baremetal-deploy/blob/c182c599c4028df6d58e525aa4e33cbea046a320/features/kubernetes-nmstate/day1/README.md)

Added a `networkData` secret in baremetalhost resource in day-2 scaling playbook, [config](https://github.com/redhat-performance/JetSki/pull/303/commits/0a5b042b759afcc54dab8c89233da1285b2837ba#diff-90fd46baa45180a38f30c9f8c3226b41311db82903645691927bd50f5117dd47R18)

Please select the appropriate options:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change is a documentation update

## Testing

- [x] 4.14.14
- [x] 4.14.18

**Test Configuration**:

- Versions: 4.14.14, 4.14.18
- Lab: scale
- Network: singlestack IPv4
- Hardware: FC640, R640 

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not be merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by mukrishn** [comment]
Tested on R650, had some lab issue but able to deploy all control plane nodes successfully. 

```
$ oc get nodes
NAME                                        STATUS   ROLES                         AGE     VERSION
f04-h09-000-r640.rdu2.scalelab.redhat.com   Ready    control-plane,master,worker   7h18m   v1.27.10+28ed2d7
f04-h10-000-r640.rdu2.scalelab.redhat.com   Ready    control-plane,master,worker   7h18m   v1.27.10+28ed2d7
f04-h11-000-r640.rdu2.scalelab.redhat.com   Ready    control-plane,master,worker   7h18m   v1.27.10+28ed2d7
```

**Comment by mukrishn** [comment]
tested deployment with [updated](https://github.com/redhat-performance/JetSki/pull/303/commits/c4c26b91940ec0e4545b3ce9e67794b34d9f69f6) config 
```
$ oc get nodes 
NAME                                        STATUS   ROLES                         AGE     VERSION
master-0                                    Ready    control-plane,master,worker   14h     v1.27.10+28ed2d7
master-1                                    Ready    control-plane,master,worker   14h     v1.27.10+28ed2d7
master-2                                    Ready    control-plane,master,worker   14h     v1.27.10+28ed2d7
```
scale worker is partially tested, need a lab allocation to test it thoroughly.

**Comment by mukrishn** [comment]
@josecastillolema @wilsondav please review

**Comment by josecastillolema** [comment]
@wilsondav can you please paste here the errors you had with this PR in *cloud18* and *cloud26*?

**Comment by josecastillolema** [comment]
Regarding the fixed hostname issue, it looks like fresh installs works fine but scale ups lack the fix, i.e.:

```
e23-h24-b03-fc640.rdu2.scalelab.redhat.com   Ready    worker                 3h41m   v1.27.11+749fe1d
e23-h24-b04-fc640.rdu2.scalelab.redhat.com   Ready    worker                 3h40m   v1.27.11+749fe1d
master-0                                     Ready    control-plane,master   5h53m   v1.27.11+749fe1d
master-1                                     Ready    control-plane,master   5h53m   v1.27.11+749fe1d
master-2                                     Ready    control-plane,master   5h52m   v1.27.11+749fe1d
worker000-fc640                              Ready    worker                 5h16m   v1.27.11+749fe1d
worker001-fc640                              Ready    worker                 5h16m   v1.27.11+749fe1d
```

Could the PR be split into two?
One for the upstream rebase and another one for the fixed hostname issue?

Thanks

**Pull request merged**
